def error(msg):
    print(msg)
    exit()
